remove electrumsys branding

diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -2,8 +2,8 @@
 
 # Parameterize
 PYTHON_VERSION=3.6.4
-BUILDDIR=/tmp/electrumsys-build
-PACKAGE=ElectrumSys
+BUILDDIR=/tmp/electrum-build
+PACKAGE=Electrum
 GIT_REPO=https://github.com/syscoin/electrum
 LIBSECP_VERSION="b408c6a8b287003d1ade5709e6f7bc3c7f1d5be7"
 
@@ -80,11 +80,11 @@ info "generating locale"
         brew install gettext
         brew link --force gettext
     fi
-    cd "$CONTRIB"/deterministic-build/electrumsys-locale
+    cd "$CONTRIB"/deterministic-build/electrum-locale
     for i in ./locale/*; do
-        dir="$ROOT_FOLDER"/electrumsys/$i/LC_MESSAGES
+        dir="$ROOT_FOLDER"/electrum/$i/LC_MESSAGES
         mkdir -p $dir
-        msgfmt --output-file=$dir/electrumsys.mo $i/electrumsys.po || true
+        msgfmt --output-file=$dir/electrum.mo $i/electrum.po || true
     done
 ) || fail "failed generating locale"
 
@@ -148,9 +148,9 @@ plutil -insert 'CFBundleURLTypes' \
 DoCodeSignMaybe "app bundle" "dist/${PACKAGE}.app" "$APP_SIGN" # If APP_SIGN is empty will be a noop
 
 info "Creating .DMG"
-hdiutil create -fs HFS+ -volname $PACKAGE -srcfolder dist/$PACKAGE.app dist/electrumsys-$VERSION.dmg || fail "Could not create .DMG"
+hdiutil create -fs HFS+ -volname $PACKAGE -srcfolder dist/$PACKAGE.app dist/electrum-$VERSION.dmg || fail "Could not create .DMG"
 
-DoCodeSignMaybe ".DMG" "dist/electrumsys-${VERSION}.dmg" "$APP_SIGN" # If APP_SIGN is empty will be a noop
+DoCodeSignMaybe ".DMG" "dist/electrum-${VERSION}.dmg" "$APP_SIGN" # If APP_SIGN is empty will be a noop
 
 if [ -z "$APP_SIGN" ]; then
     warn "App was built successfully but was not code signed. Users may get security warnings from macOS."
